# CMI
destination: "../cmi-www/t/acim"

sourceId: 12
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'ACIM Sparkly Edition'
tagline:      'Sparkly Edition'
description:  ''
url:          'https://www.christmind.info/t/acim'
baseurl:      ''
keywords:     "Christ Mind Teachings, A Course in Miracles, Sparkly Edition "
port:         9912

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://www.christmind.info/t/acim'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-sitemap

# Collections for transcripts
collections:
  acq:
    output: true
    title: "Get Acquainted"
  text:
    output: true
    title: "A Course in Miracles: Text"
  workbook:
    output: true
    title: "A Course in Miracles: Workbook"
  manual:
    output: true
    title: "A Course in Miracles: Manual"
  preface:
    output: true
    title: "Preface to the ACIM Sparkly Edition"

defaults:
  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/acim/public/img/acim/acq-big.jpg"
      image-width: 612
      image-height: 792
      audio: false
      bid: "acq"
      pnumToggle: false
  - scope:
      path: ""
      type: text
    values:
      layout: transcript
      book: "Text"
      image: "/t/acim/public/img/acim/text.jpg"
      image-width: 612
      image-height: 792
      bid: "text"
      audio: false
  - scope:
      path: ""
      type: workbook
    values:
      layout: transcript
      book: "Workbook for Students"
      image: "/t/acim/public/img/acim/workbook.jpg"
      image-width: 612
      image-height: 792
      bid: "workbook"
      audio: false
  - scope:
      path: ""
      type: manual
    values:
      layout: transcript
      book: "Manual"
      image: "/t/acim/public/img/acim/manual.jpg"
      image-width: 612
      image-height: 792
      bid: "manual"
      audio: false
  - scope:
      path: ""
      type: preface
    values:
      layout: transcript
      book: "Preface"
      image: "/t/acim/public/img/acim/preface.jpg"
      image-width: 612
      image-height: 792
      bid: "preface"
      audio: false

exclude: [
  moved.html, deploy, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

